# Generated by Django 2.2.7 on 2020-01-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authority',
            options={'verbose_name_plural': 'Authorities'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='frequency',
            options={'verbose_name_plural': 'Frequencies'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='sources',
            options={'verbose_name_plural': 'Sources'},
        ),
        migrations.AlterField(
            model_name='masterrulebook',
            name='initial_date_of_rendition',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
