# Generated by Django 2.2.7 on 2020-01-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20200103_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrulebook',
            name='initial_date_of_rendition',
            field=models.DateField(blank=True, null=True),
        ),
    ]
