# Generated by Django 2.2.7 on 2020-01-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20200103_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrulebook',
            name='initial_date_of_rendition',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
