# Generated by Django 2.2.7 on 2020-01-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_auto_20200103_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterrulebook',
            name='sanctions',
            field=models.CharField(default='nothing at all', max_length=200),
        ),
    ]
