# Generated by Django 2.2.7 on 2020-01-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_masterrulebook_sanctions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrulebook',
            name='sanctions',
            field=models.CharField(default='Shall Attract Appropriate Sanctions', max_length=200),
        ),
    ]
