# Generated by Django 2.2.7 on 2020-01-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_auto_20200113_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='owner',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
